apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "tooling.labels" . | nindent 4 }}
  annotations:
    {{- include "tooling.annotations" . | nindent 4 }}
type: Opaque
data:
  secure-password-1: aS1hbS1lbmNvZGVkLXNlY3JldC0xCg==
  secure-password-2: aS1hbS1lbmNvZGVkLXNlY3JldC0yCg==
