apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}
  annotations:
    {{- include "tooling.annotations" . | nindent 4 }}
  labels:
    {{- include "tooling.labels" . | nindent 4 }}
    app.kubernetes.io/component: "api"
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "tooling.selectorLabels" . | nindent 4 }}
